version: '3.6'
services:
  #MariaDb Service
  my-lead-db:
    image: mariadb:10.3.27
    container_name: my-lead-db
    restart: unless-stopped
    tty: true
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    volumes:
      - my_lead_db_data:/var/lib/mysql-files/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  my_lead_db_data:
    driver: local
